# Generated by Django 6.0 on 2026-01-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-created_time"],
                "verbose_name": "commentary",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(verbose_name="Add commentary: "),
        ),
    ]
